### ISSUE TITLE
Possible name conflict

### ISSUE THREAD

**Issue by robsonpeixoto** [nicholasjackson/terraform-digitalocean-lifecycle#1]
You are defining the **name** using the `count.index` without a [random string](https://www.terraform.io/docs/providers/random/r/string.html).
Should didn't it cause a name conflict in the cloud provider, because the new resource has the same name of the old resource?

```tf
resource "digitalocean_droplet" "web" {
  // ...
  name   = "web-${count.index}"
  // ...
}
```

**Comment by nodesocket** [comment]
In DigitalOcean name is just a label. You can have multiple droplets with the same name.
